"""Glossary content for the Reinforcement Learning Concepts page."""

import rl_gridworld as g

P = {
    "episodes": g.EPISODES,
    "max_steps": g.MAX_STEPS,
    "gamma": g.GAMMA,
    "epsilon_start": g.EPSILON_START,
    "epsilon_min": g.EPSILON_MIN,
    "epsilon_decay": g.EPSILON_DECAY,
}

GLOSSARY = [
  {"icon": "bi-question-circle", "term": "What is Reinforcement Learning?",
   "text": f"Reinforcement Learning (RL) is a way of learning by <strong>trial and error</strong>. An agent interacts with an environment, receives rewards or penalties for what it does, and gradually learns which behavior maximizes the total reward. There are no labeled examples (as in supervised learning) and no groups to discover (as in unsupervised learning): the only teacher is the reward signal.",
   "example": f"A virtual robot learns, only from rewards, how to cross a 10 × 10 maze from A to T while avoiding walls and danger zones."},
  {"icon": "bi-robot", "term": "Agent",
   "text": f"The entity that observes the state, chooses an action and learns from the result.",
   "example": f"The virtual robot that starts on the cell marked <code>A</code>. Nobody programs its route; it only decides between Up, Down, Left and Right."},
  {"icon": "bi-grid-3x3-gap", "term": "Environment",
   "text": f"Everything the agent interacts with. It defines the rules: what each action does and which reward is returned.",
   "example": f"The 10 × 10 grid with walls (<code>#</code>), danger zones (<code>D</code>), free cells (<code>o</code>) and the target (<code>T</code>), plus the movement rules implemented in the <code>step()</code> function."},
  {"icon": "bi-geo-alt", "term": "State (s)",
   "text": f"A description of the situation of the agent at a given moment.",
   "example": f"The robot's current <strong>(row, column)</strong>, for example <code>(0,0)</code> at the start. There are 100 positions; 79 of them are cells the robot can stand on and still has to decide an action from (walls cannot be entered and the target ends the episode)."},
  {"icon": "bi-arrows-move", "term": "Action (a)",
   "text": f"A decision the agent can take in a state.",
   "example": f"Exactly four actions: <strong>Up, Down, Left, Right</strong>. The agent cannot leave the grid or cross a <code>#</code>."},
  {"icon": "bi-trophy", "term": "Reward (r)",
   "text": f"A number returned by the environment after every action that tells the agent how good that action was.",
   "example": f"-1 for each normal move (so shorter routes are better) and +100 for reaching the target."},
  {"icon": "bi-exclamation-octagon", "term": "Penalty",
   "text": f"A negative reward used to discourage undesirable behavior.",
   "example": f"-5 for trying to leave the grid, -8 for hitting a wall and -25 for entering a danger zone <code>D</code>. In the last case the move <em>is</em> allowed, but it is expensive."},
  {"icon": "bi-signpost-split", "term": "Policy (&pi;)",
   "text": f"The rule the agent follows to pick an action in each state. Learning a good policy is the goal of RL.",
   "example": f"After training, the policy is greedy: <code>&pi;(s) = argmax<sub>a</sub> Q(s,a)</code>. The final route emerges from the learned Q-values; it is never written by hand."},
  {"icon": "bi-footsteps", "term": "Step",
   "text": f"One interaction cycle: the agent chooses an action, the environment answers with the next state and a reward.",
   "example": f"Moving from <code>(0,0)</code> to <code>(0,1)</code> with Right is one step with reward -1. An episode may not exceed <strong>{P['max_steps']} steps</strong>."},
  {"icon": "bi-arrow-repeat", "term": "Episode",
   "text": f"A complete attempt: it starts at the initial state and ends when a terminal condition occurs.",
   "example": f"An episode begins at <code>A</code> and ends when the robot reaches <code>T</code> or uses up the maximum number of steps. The agent is trained for <strong>{P['episodes']} episodes</strong>."},
  {"icon": "bi-journal-text", "term": "Experience",
   "text": f"What the agent remembers from one step, as a tuple <code>(s, a, r, s')</code>. Learning happens from experiences.",
   "example": f"<code>((0,0), Right, -1, (0,1))</code> is one experience: from (0,0) the agent moved Right, received -1 and landed on (0,1)."},
  {"icon": "bi-compass", "term": "Exploration",
   "text": f"Trying actions at random to discover how the environment responds, even if they do not look best yet.",
   "example": f"At the beginning the robot knows nothing about the maze, so it must wander, bump into walls and even step on a <code>D</code> to find out what happens."},
  {"icon": "bi-bullseye", "term": "Exploitation",
   "text": f"Choosing the action with the highest estimated value, using what has already been learned.",
   "example": f"Once the Q-values show that Right is best from (0,0), exploiting means taking Right."},
  {"icon": "bi-percent", "term": "Epsilon-Greedy strategy",
   "text": f"A rule that balances both: with probability <strong>&epsilon;</strong> the agent explores (random action); with probability <strong>1 - &epsilon;</strong> it exploits (best Q-value). &epsilon; shrinks during training so the agent explores a lot at first and acts on its knowledge later.",
   "example": f"&epsilon; starts at {P['epsilon_start']}, is multiplied by {P['epsilon_decay']} after every episode and never goes below {P['epsilon_min']}."},
  {"icon": "bi-lightning-charge", "term": "Immediate reward",
   "text": f"The reward <em>r</em> received right after one action, without looking at the future.",
   "example": f"Entering a danger zone costs -25 immediately, while stepping onto a normal cell costs -1."},
  {"icon": "bi-cash-stack", "term": "Return (G)",
   "text": f"The total reward accumulated from a moment onward, with future rewards discounted: <code>G = r<sub>1</sub> + &gamma; r<sub>2</sub> + &gamma;<sup>2</sup> r<sub>3</sub> + ...</code>. RL maximizes the expected return, not just the immediate reward.",
   "example": f"Walking 19 normal cells (-1 each) and then reaching T (+100) gives an undiscounted return of <strong>81</strong>. A route through a <code>D</code> is shorter but loses 25, so its return is lower."},
  {"icon": "bi-hourglass-split", "term": "Discount factor (&gamma;)",
   "text": f"A number between 0 and 1 that says how much future rewards count compared with immediate ones. Close to 0 the agent is short-sighted; close to 1 it values long-term reward.",
   "example": f"&gamma; = {P['gamma']}: the +100 waiting about 20 steps away still has a strong influence on the very first move."},
  {"icon": "bi-graph-up", "term": "State value V(s)",
   "text": f"The expected return of being in state <em>s</em> and following the policy from there on.",
   "example": f"For the greedy policy, <code>V(s) = max<sub>a</sub> Q(s,a)</code>. A cell close to T has a high V; a cell far from T, or next to dangers, has a lower one."},
  {"icon": "bi-table", "term": "Action value Q(s,a)",
   "text": f"The expected return of taking action <em>a</em> in state <em>s</em> and then following the policy. Q tells the agent which action is best in each state.",
   "example": f"The Application page shows, for every state, four numbers: Q(s,Up), Q(s,Down), Q(s,Left) and Q(s,Right). The largest one is the action the trained agent takes."},
  {"icon": "bi-cpu", "term": "Q-Learning",
   "text": f"An algorithm that learns Q(s,a) from experience. After every step it moves the current estimate toward the target <code>r + &gamma; &middot; max<sub>a'</sub> Q(s',a')</code>. In this exercise Q is approximated by scikit-learn's <code>SGDRegressor</code>: <code>predict()</code> estimates the Q-values and <code>partial_fit()</code> updates the model with the observed transitions (incremental learning).",
   "example": f"Each (state, action) pair is encoded as a one-hot vector of 400 features (100 states &times; 4 actions), so the model keeps one learnable value per pair."}
]
